services:
  frontend:
    build:
      context: .
      args:
        VITE_API_BASE_URL: /api
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    environment:
      - NODE_ENV=production
    networks:
      - appointment-net

networks:
  appointment-net:
    external: true
